// Code generated by mockery v2.46.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Producer is an autogenerated mock type for the Producer type
type Producer struct {
	mock.Mock
}

// PublishMsg provides a mock function with given fields: msgType, data, topic
func (_m *Producer) PublishMsg(msgType string, data any, topic string) error {
	ret := _m.Called(msgType, data, topic)

	if len(ret) == 0 {
		panic("no return value specified for PublishMsg")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, any, string) error); ok {
		r0 = rf(msgType, data, topic)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewProducer creates a new instance of Producer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *Producer {
	mock := &Producer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
