version: "3.9"

services:
  urleater:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./build/local/docker.env
    command:
      - "./entrypoint.sh"
    networks:
      - backend
    depends_on:
      - postgres-urleater
      - elasticsearch
      - kafka
      - redis
  postgres-urleater:
    image: postgres:14-alpine
    container_name: postgres-urleater
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  # 🔹 PgAdmin (UI для PostgreSQL)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container_urleater
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 1234
    networks:
      - backend

  # 🔹 Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false  # ❗ Отключает защиту

    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - backend

  # 🔹 Redis
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend
    volumes:
      - redis_data:/data

  # 🔹 Zookeeper (требуется для Kafka)
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - backend

  # 🔹 Kafka Broker
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092

    ports:
      - "9092:9092"
    networks:
      - backend


networks:
  backend:
    driver: bridge

volumes:
  elasticsearch_data:
  redis_data:
  kafka_data:
  postgres_data:
