Feature:
  Scenario Outline: Create Shortlink with autogenerated link
    Given I have logged in
    And I clicked on create short link tab
    When I type <long_url>
    And I choose automatic generation
    And I click on create button
    Then I get newly generated Link

    Examples:
      | long_url                                                                                         |
      | https://www.jetbrains.com/help/inspectopedia/CucumberUndefinedStep.html#locating-this-inspection |
      | https://stackoverflow.com/questions/60948850/godog-pass-arguments-state-between-steps            |

  Scenario Outline: Create Shortlink with alias
      Given I have logged in
      And I clicked on create short link tab
      When I type url <long_url>
      And I choose generation
      And I type alias <alias>
      And I click on create button
      Then I get newly generated Link with alias <alias>

    Examples:
      | long_url                                                                                         | alias       |
      | https://www.jetbrains.com/help/inspectopedia/CucumberUndefinedStep.html#locating-this-inspection | firstlink1  |
      | https://stackoverflow.com/questions/60948850/godog-pass-arguments-state-between-steps            | secondlink2 |